### ISSUE TITLE
FEATURE - Persist generated mockdata

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-odata#144]
_As a **developer**,
I want to **the option to write the generated mockdata to the filesystem**,
so that I **manipulate it to my needs**_.

### Description
I am heavily using the `generateMockData: true` feature with new projects since I don't need more specific mockdata for many of my tests. However, sometimes, I would like to slightly modify it for my needs, therefore, I would like to get a way to generate the mockdata and then being able to manipulate it.
I could see following options:
1. get a cli command e.g. `mock generate` 
2. have an additional flag that writes the mockdata to the filesystem when I run it the first time

### Technical Design
_What modules need to be created or enhanced?_ 
_How would the functionality be exposed and how can it be consumed?_

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have a the feature
**when** I execute `mock generate` and then manipulate the mockdata files to my needs
**then** I will be able to better test my application with mockdata.

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by jberthe** [comment]
Hi, 

If you want to use you custom data for specific entity set, you can add a JSON file in the **/localService/data**.

If you have an entity set named SalesOrdes then the file should be named : **SalesOrders.json**, the middlewear will use that file instead of the generated data.

Regards,

**Comment by tobiasqueck** [comment]
We can actually close this feature request since there is an alternative available in the SAP Fiori tools. More information at https://github.com/SAP/open-ux-odata/discussions/194.
