### ISSUE TITLE
BUG - content-type missing in response when throwing error

### ISSUE THREAD

**Issue by nilsbrenker** [SAP/open-ux-odata#236]
### Description
I'm throwing an error message within the `addEntry` function, but the error is not displayed by Fiori Elements (v4) because the content-type is missing.

### Steps to Reproduce
Throwing an error in the addEntry function:

```
this.throwError('Error', 400, {
    error: {
        code: 400,
        message: "Field 'Field1' is required.",
        target: "in/field1"
    }
});
```

### Expected results

```
HTTP/1.1 400 Bad Request
odata-version: 4.0
content-type: application/json;odata.metadata=minimal;IEEE754Compatible=true

{"error":{"code":400,"message":"Field 'Field1' is required.","target":"in/field1"}}

```

### Actual results

```
HTTP/1.1 400 Bad Request
odata-version: 4.0

{"error":{"code":400,"message":"Field 'Field1' is required.","target":"in/field1"}}
```

### Own analysis
I tried locally to add the content-type [here](https://github.com/SAP/open-ux-odata/blob/1d0ea1c6884aa909a9afe82c16e57e69cd8567be/packages/fe-mockserver-core/src/request/odataRequest.ts#L397) and  it worked for me.

#### Version/Components/Environment	
Running on latest mockserver version 2.1.25

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Hi @nilsbrenker thanks for the bug report, i have create PR #237 in order to solve it :)

**Comment by nilsbrenker** [comment]
Retest on v2.1.26 was successful, many thanks for the fast fix!!
