### ISSUE TITLE
FEATURE - [Annotation Converter] Revert an object of different EdmTypes to its raw value

### ISSUE THREAD

**Issue by anjan-poonacha** [SAP/open-ux-odata#287]
_As a **developer**,
I want to **have option to convert all type of object to its raw value**,
so that I **can use it to generate annotations correctly**_

### Description

_What is the high level purpose and value of the feature?  The description should ensure that anyone reading understands what it is doing (at a high level) and most importantly why._

With this we will be able to write annotation which looks like this into the annotation file. 
Scope of this is to add support for Int, Float, Boolean, Date, DateTimeOffset, Binary
```xml		
				
                <Annotation Term="Common.FilterDefaultValue" Date="2099-08-09" />
                <Annotation Term="Common.FilterDefaultValue" Int="10" />
                <Annotation Term="Common.FilterDefaultValue" Float="10.0" />
         
```

### Technical Design
_What modules need to be created or enhanced?_  -> Annotation-Converter

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

### Tasks

- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by nlunets** [comment]
@anjan-poonacha this is done right ? If so we can close this ?

**Comment by anjanpoonacha** [comment]
@nlunets Yes. Please do. I do not have the permission.

**Comment by anjan-poonacha** [comment]
@nlunets Yes. Closing this.
