### ISSUE TITLE
Mock Preview is not displaying quantities in V4 APP

### ISSUE THREAD

**Issue by BB-21** [SAP/open-ux-odata#312]
V4 Fiori APP. Manage physical stock-products has OPA5 Tests and mock data. In BAS when we preview APP with mock.yaml file i.e. start  mock. it displays 5 products from warehouse EWM1.
preview in list report page is not showing quantitiy fields eventhough quantities are in WarehousePhysicalStockProducts.json file.
What is missing in mockdata? do we need to add unitmetadata as JSON file in Mockdata?if yes, how it should be named?

FYI: LR ,OP are FE pages. APP has freestyle page Action.

### Description
Mock preview does not display quantities fields in LR, OP.see screenshot below.
![image](https://user-images.githubusercontent.com/87657005/195550397-2adb866a-0a3e-4411-a96e-b6089d9c1199.png)

console has following error.
![image](https://user-images.githubusercontent.com/87657005/195551137-c15713a7-df9b-42a5-9765-54ee87b7bf57.png)

### Steps to Reproduce
GITREPO: https://github.tools.sap/S4-FIORI-CORE-7/scm.ewm.physstocks1.git

pls clone above GIT Repo. Main Branch has OPA5 Tests and Mock data files.

### Expected results

LR,OP must display all the info from Json file. Quantities are not displayed in LR and OP.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                 

- [X ] Windows

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
From what i can see you probably are missing the service call to retrieve the unit / currency.
This is usually a service starting by iwbep that you would need to mock as well :)

**Comment by BB-21** [comment]
yes, you are right. I missed it. Thanks.
