### ISSUE TITLE
Package '@sap-ux/vocabularies-types': Wrong supported node versions in public npm

### ISSUE THREAD

**Issue by cloudyafternoon** [SAP/open-ux-odata#346]
It seems that in public npm, the supported node versions are still 
`'>=12.22.5 < 13.0.0 || >= 14.16.0 < 15.0.0 || >=16.1.0 < 17.0.0'`

In this repo, the versions are already updated:
packages/vocabularies-types/package.json has string `">= 14.16.0 < 15.0.0 || >=16.1.0 < 17.0.0 || >=18.0.0 < 19.0.0"`

Can you check if deployment to npm public repo was successful and potentially re-trigger it?

On node 18, I get:

```npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@sap-ux/vocabularies-types@0.5.7',
npm WARN EBADENGINE   required: {
npm WARN EBADENGINE     pnpm: '>=6.26.1',
npm WARN EBADENGINE     node: '>=12.22.5 < 13.0.0 || >= 14.16.0 < 15.0.0 || >=16.1.0 < 17.0.0'
npm WARN EBADENGINE   },
npm WARN EBADENGINE   current: { node: 'v18.12.1', npm: '8.19.2' }
npm WARN EBADENGINE }```

**Comment by nlunets** [comment]
The version on npmjs is 0.6.8 which supports up to node 18
I'd suggest you update the version of the package you are using that consumes the vocabularies-types (I guess the mockserver ?)
