### ISSUE TITLE
BUG - Wrong default record type in converted metadata

### ISSUE THREAD

**Issue by vadson71** [SAP/open-ux-odata#357]
### Description
ODATA standard allows to omit record type attribute in annotations in case when there is no ambiguity, and the record type could be determined from the context (parent element type and its property name). 
If record type is not explicitly provided in annotation, then in converted metadata its type is calculated incorrectly - seem to be directly taken from parent element type.

### Steps to Reproduce
1. Here is a sample project.
[TechEd2.zip](https://github.com/SAP/open-ux-odata/files/10110824/TechEd2.zip)
Please find UI.SelectionPresentationVariant annotation in manage_travels/wepapp/annotations/annotation.xml file. In the property   "PresentationVariant" value record type is not specified and implicitly considered as UI.PresentationVariantType.
![image](https://user-images.githubusercontent.com/6931493/204473130-81179523-eeb0-4fce-aced-5194da81cd2f.png)

2. In debugger result of project data conversion is following:
![image](https://user-images.githubusercontent.com/6931493/204471895-569dd117-f183-44ea-b3bf-229f46ac9b8b.png)
The omitted record type is incorrectly inherited from parent record. SelectionVariant property contains correct type as it was explicitly provided in the annotation

### Expected results
PresentationVariant property record should be "com.sap.vocabularies.UI.v1.PresentationVariantType"

### Actual results
PresentationVariant property record is the same as parent record type "com.sap.vocabularies.UI.v1.SelectionPresentationVariantType".

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [x] Windows
- [ ] Other

**Comment by nlunets** [comment]
This was fixed with the above commit (or at least improved)
Latest version should have what you need [@sap-ux/vocabularies-types@0.7.0](https://github.com/SAP/open-ux-odata/releases/tag/%40sap-ux%2Fvocabularies-types%400.7.0)
