### ISSUE TITLE
BUG - Invalid boundary while parsing batch request (@sap-ux/ui5-middleware-fe-mockserver) with karma

### ISSUE THREAD

**Issue by tobiasso85** [SAP/open-ux-odata#394]
Error `Invalid boundary while parsing batch request` occurred when running `ui5-middleware-fe-mockserver` after `compression` task within [karma-ui5](https://github.com/SAP/karma-ui5)

### Features
@sap-ux/ui5-middleware-fe-mockserver

### Description
when running the mockserver within `karma-ui5`, OData $batch requests fail with `Invalid boundary while parsing batch request`.
The batch request's body becomes `{}`

* ui5.yaml

```
...
server:
  customMiddleware:
    - name: sap-fe-mockserver
      afterMiddleware: compression
...
```

see related:
* https://github.com/SAP/karma-ui5/issues/410
* https://github.com/SAP/karma-ui5/issues/344

### Workaround
When changing
```
afterMiddleware: compression
```
to
```
beforeMiddleware: csp
```
it works.

### Expectation
Documentation of the issue or fix

**Comment by nlunets** [comment]
HI @tobiasso85 thanks for this, we actually had that in the readme before but i can't find it so we probably lost it during migration.
Will update this :)

**Comment by nlunets** [comment]
Documentation update in main, will be included in the next release !
