### ISSUE TITLE
BUG - ui5-middleware-fe-mockserver fails to start with UI5 Tooling v3 RC

### ISSUE THREAD

**Issue by zdravko-georgiev** [SAP/open-ux-odata#409]
### Description
While testing the https://www.npmjs.com/package/@ui5/cli/v/3.0.0-rc.2 I run into the issue that the `ui5-middleware-fe-mockserver` fails to start with the following exception:

![mockserver](https://user-images.githubusercontent.com/91968887/214071814-045db59b-2224-4929-8575-9f0c9969e870.png)

The root cause of the issue is the use of a [private API](https://github.com/SAP/open-ux-odata/blob/main/packages/ui5-middleware-fe-mockserver/src/index.ts#L10) that has been removed in v3.

Solution proposal by @RandomByte:

>The middleware **needs to be adapted**. It should declare `specVersion: 3.0` in the ui5.yaml and access the root project using our newly added API: `taskUtil.getProject()` ([example](https://sap.github.io/ui5-tooling/v3/pages/extensibility/CustomTasks/#example-libtaskscompilelicensesummaryjs); [API reference](https://sap.github.io/ui5-tooling/v3/api/@ui5_project_build_helpers_TaskUtil.html#getProject)).
>
>On the returned [ProjectInterface](https://sap.github.io/ui5-tooling/v3/api/@ui5_project_build_helpers_TaskUtil.html#~ProjectInterface), you can then use the `getSourcePath()` method to get the expected "webapp" path. Note that this API is not available in RC2, but probably in the next release (see https://github.com/SAP/ui5-project/pull/549).

### Steps to Reproduce
1. Install `3.0.0-rc.2` of `@ui5/cli`
2. Try to start the `ui5-middleware-fe-mockserver`
3. See error

### Expected results
`ui5-middleware-fe-mockserver` starts successfully

### Actual results
`ui5-middleware-fe-mockserver` fails to start

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [x] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by RandomByte** [comment]
We just published the required UI5 CLI Release Candidate 3. You can install it via `npm i --save-dev @ui5/cli@next`

**Comment by nlunets** [comment]
@RandomByte will declaring spec3.0 allow the middleware to be used in prior version of the ui5 cli ?

**Comment by RandomByte** [comment]
Hey Nicolas, sadly no. Changing the specVersion in an extension should be treated as a breaking change. Only compatible versions of UI5 CLI will be able to use it:
https://sap.github.io/ui5-tooling/v3/pages/Configuration/#compatibility-matrix

Specification Version 3.0 will only be compatible with UI5 CLI 3.0.0 and later.

**Comment by nlunets** [comment]
Then that's unfortunately not really an option for us.
I'll see what I can find as alternative

**Comment by nlunets** [comment]
By the way, forgot to mention but this has been working for some time now, you can check the latest version if you want

@sap-ux/ui5-middleware-fe-mockserver@2.1.60

**Comment by zdravko-georgiev** [comment]
Thanks @nlunets!
