### ISSUE TITLE
FEATURE - mockserver - api to implement missing referential constraints 

### ISSUE THREAD

**Issue by antoine42** [SAP/open-ux-odata#416]
Some odata servers may not provide referential constraints in the metadata for all kinds of navigation properties.

Therefore, when trying to use $expand on such navigation properties, the mock server doesn't now how to compute the link.

For example, using CAPM the following composition 
```
@readonly
@title:'{i18n>CONNECTED_SYSTEM_COMMUNICATION_ARRANGEMENT}'
communicationArrangements: composition of many CommunicationArrangement on communicationArrangements.connectedSystemId = code;
```

is translated as
```
<NavigationProperty Name="communicationArrangements" Type="Collection(AdminServiceV5.CommunicationArrangements)">
  <OnDelete Action="Cascade"/>
</NavigationProperty>
```

We would need to find a way to implement such relationship in the mock server so it can implement $expand properly.

We are using the fe mockserver to run opa tests on productive apps and produce a code coverage report.

**Comment by nlunets** [comment]
Hi @antoine42 thanks for the report, 

Before we look into this in more detail, would it be a solution for you to provide the data inline of the parent entity such as

```
{
   communicationArrangements: [....]
}
```

for each entry or would that make no sense ?

**Comment by nlunets** [comment]
Available in @sap-ux/ui5-middleware-fe-mockserver@2.1.57
