### ISSUE TITLE
FEATURE - Sorting (orderby) of complex types

### ISSUE THREAD

**Issue by Siolto** [SAP/open-ux-odata#417]
As a developer,
I want to sort on properties that are defined in complex types,
so that I can test my sorting on tables without the real backend

### Description

I have the requirement to sort on properties that are defined in a Complex Type. My Request looks something like this:

`<EntitySet>?$orderby=<complexTypeName>/<property> asc`

The Filter on complex types is already working:

`<EntitySet>?$filter=<complexTypeName>/<property> eq 10`

**Comment by nlunets** [comment]
Confirmed that this is required, will prepare a change :)

**Comment by nlunets** [comment]
Fixed with @sap-ux/ui5-middleware-fe-mockserver@2.1.60
