### ISSUE TITLE
BUG -  404 Not Found error with certain FE mockserver version

### ISSUE THREAD

**Issue by mengmengh2022** [SAP/open-ux-odata#467]
### Description
In our Fiori Elements V4 app the mockserver throws "**Communication error: 404 Not Found**" in certain cases with FE mockserver version higher than 2.1.19. Before the version update everything is working without error. This is blocking us from updating the version.

#### Scenario 1:
With  @sap-ux/ui5-middleware-fe-mockserve version **2.1.62**, the data in 'UI.DataFieldForAnnotation' cannot be displayed. The errors are:
```
Failed to read path /Issues(ID=87f12d6a-ea57-41b7-bf82-c5e720721f5a,IsActiveEntity=true)/owner/department - Error: Communication error: 404 Not Found
Failed to read path /Issues(ID=87f12d6a-ea57-41b7-bf82-c5e720721f5a,IsActiveEntity=true)/owner/email - Error: Communication error: 404 Not Found

```
With  "@sap-ux/ui5-middleware-fe-mockserver": "**2.1.43**" it is working.

#### Scenario 2:
With mockserver version higher than **2.1.19**, we get "Communication error: 404 Not Found", after executing following custom code:

```
      let oContext = oBinding.create({
          "conclusionDetail_ID": oSelectedConclusionDetail,
          "issueContextConclusionAssignment_ID": oIssueContextConclusionAssignmentId
      });
```

Error logs:
```
Log-dbg.js:452 2023-03-14 11:34:53.654699 
Failed to refresh entity: /Applications(ID=abce3d5b-4f74-4faa-a76b-7f6f20271c97,IsActiveEntity=false)/issueContextConclusionAssignments(ID=22eeb349-999b-4855-8f18-ae8e49f1552a,IsActiveEntity=false)/conclusionDetailAssignments(ID=08984d79-6ecf-4a29-a6fe-f1372363f9ee,IsActiveEntity=false)[-1;transient] 
- Error: Communication error: 404 Not Found
    at Object.createError (http://localhost:3000/resources/sap/ui/core/library-preload.js:2226:2563)
    at http://localhost:3000/resources/sap/ui/core/library-preload.js:2256:11100
    at Array.forEach (<anonymous>)
    at a (http://localhost:3000/resources/sap/ui/core/library-preload.js:2256:10850)
    at http://localhost:3000/resources/sap/ui/core/library-preload.js:2256:11841 sap.ui.model.odata.v4.ODataListBinding
```

When using mockserver version **2.1.19** it is working without error.
 
  

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Hi @mengmengh2022 would it be possible for you to provide the queries that are causing issues ?

**Comment by nlunets** [comment]
Ok for this one seems like we are not creating the object in the right place so that doesn't help :)

**Comment by mengmengh2022** [comment]
Thank you Nicolas, 
with 2.1.71 the problem in Scenario 2 is resolved.
But the problem in Scenario 1 is still existing.  
Best regards,
Mengmeng

**Comment by nlunets** [comment]
That's why you don't create 2 issues in one ticket :)
