### ISSUE TITLE
BUG - Autogeneration of "Missing" Keys 

### ISSUE THREAD

**Issue by zaid-tariq** [SAP/open-ux-odata#475]
### Related Feature
Feature request: _issue number_

### Description
If some key is "missing", it is auto-generated. 
I think it is undesirable. 
Sometimes, the key is intentionally left blank to test the behaviour of the app. In this case, the "missing" keys should not be auto-generated.

### Steps to Reproduce
Make a post request with 2 or more keys.
Enter one key, leave the others as empty strings.
Put a debug point in entitySet.js > performPOST.
Note that the method generates fakes for all the keys that are undefined or empty strings.

### Expected results
No auto-generation of missing keys.

### Actual results
Keys are auto-generated.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- Mac OS

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Hi @zaid-tariq keys are mandatory to get data.

We don/t have a specific algorithm for them but any property that is not nullable needs a value from the odata specification perspective so we make sure to fill in the gaps.

This is especially true for POST as we need to be able to address the newly created items.

If you have a very special use case we could add a flag to disable this but i'm really not convinced

**Comment by nlunets** [comment]
feel free to reopen if you disagree and have. good case
