### ISSUE TITLE
SonarCloud Setup

### ISSUE THREAD

**Issue by tobiasqueck** [SAP/open-ux-odata#5]
### Description (include screenshots)
Configure the project to use https://sonarcloud.io/.

### Value
Being able to continuously watch code quality helps keeping the code base maintainable.

### Architecture Elaboration
Not really, but a technical investigation.

**Comment by kranthie-sap** [comment]
Support added in PR https://github.com/SAP/open-ux-odata/pull/55.

**Comment by nlunets** [comment]
Sonar works fine, thanks @kranthie-sap
