### ISSUE TITLE
BUG - Karma test fails with version >2.1.67

### ISSUE THREAD

**Issue by juergenbosch** [SAP/open-ux-odata#504]
We have an internal repository that worked with previous version of the mockserver, however, since version `2.1.67` it fails. I will share the repository through a different channel.

To Reproduce checkout and execute:
`npm test`

**Comment by nlunets** [comment]
Hi Juergen,

npm test doesn't work indeed even if I npm install first :)

The fact that it runs headless and that you have 24 test also doesn't help me pinpoint what might be wrong.

I took a chance and ran, `npm start-mock` but that also doesn't work as there is a missing reuse library, i see no reference or information about it on your repo.

As such right now i cannot process this ticket.
Feel free to send me more details by mail.
