### ISSUE TITLE
BUG - Descending sort returns an error on Tree table

### ISSUE THREAD

**Issue by GwendalMoreau** [SAP/open-ux-odata#519]
### Related Feature
Feature request: _issue number_

### Description

Descending sort on a Tree table (hierarchical query) returns a parsing error:

### Steps to Reproduce
1. Go to sap.fe demokit: http://localhost:8080/test-resources/sap/fe/templates/internal/demokit/technicalSandbox.html#Hierarchy-manage?sap-ui-app-id-hint=Hierarchy-manage
2. Do a descending sort on any column
3. Error returns by the mock server:

### Expected results
Descending sort should not return any error and should be applied

### Actual results
Error from Mock server when applying a descending sort

### Screenshots
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/13252299/229540742-61aeecac-4757-4c11-aedd-c956a93bd2e4.png">

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Fixed in the latest version
