### ISSUE TITLE
BUG - Leaf displayed as node when doing ExpandAll on Tree Table

### ISSUE THREAD

**Issue by GwendalMoreau** [SAP/open-ux-odata#520]
### Related Feature
Feature request: _issue number_

### Description

With the FE mock server, when performing an ExpandAll on a Tree table, Leafs are displayed as expanded node (i.e all elements have a DrillState = expanded)/

ExpandAll
<img width="262" alt="image" src="https://user-images.githubusercontent.com/13252299/229541642-57f72876-c518-4a4f-b682-19b537d3491d.png">

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/13252299/229542237-c12e8646-72d7-4584-a386-f4c85768f000.png">

Manual expand
<img width="231" alt="image" src="https://user-images.githubusercontent.com/13252299/229541799-9ef16057-f371-438f-aa49-59dba9af0383.png">

### Steps to Reproduce
http://localhost:8080/test-resources/sap/fe/templates/internal/demokit/technicalSandbox.html#Hierarchy-manage?sap-ui-app-id-hint=Hierarchy-manage

### Expected results
When performing an ExpandAll the DrillState should be correct

### Actual results
When performing an ExpandAll , leafs are displayed as expanded node (i.e all elements have a DrillState = expanded)/

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Fixed in the latest version
