### ISSUE TITLE
BUG - typo in the ui5-middleware-fe-mockserver README.md

### ISSUE THREAD

**Issue by helencorrigan** [SAP/open-ux-odata#530]
### Description
The readme file for ui5-middleware-fe-mockserver looks to have a typo on the page: https://github.com/SAP/open-ux-odata/blob/main/packages/ui5-middleware-fe-mockserver/README.md

### Steps to Reproduce
1. Go to readme.md file : : https://github.com/SAP/open-ux-odata/blob/main/packages/ui5-middleware-fe-mockserver/README.md
2. Scroll down to the Usage section
3. locate the text "the npm module @sap/ux-ui5-fe-mockserver-middleware"

### Expected results
the npm module @sap-ux/ux-ui5-fe-mockserver-middleware 

### Actual results
the npm module @sap/ux-ui5-fe-mockserver-middleware 

### Screenshots
![ui5-middleware-fe-mockserver_readme_typo](https://user-images.githubusercontent.com/23521075/231692557-c06fa095-accd-492a-8aa7-092963313c70.jpg)

If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by helencorrigan** [comment]
FYI @nlunets

**Comment by nlunets** [comment]
Should be resolved with the latest published version !
