### ISSUE TITLE
BUG - Additional apostrophes are included in the key strings of parameter keys of function executeAction of V4 mock server

### ISSUE THREAD

**Issue by D061072** [SAP/open-ux-odata#540]
### Description
For the FE V4 app we are using the mock server for mocking some actions. In the V4 mock server there is function executeAction for that. The parameter keys contains all key strings for the current entity. However, in the key strings, there are additional apostrophes ('). 
We need to remove these apostrophes, before we use the keys.

### Steps to Reproduce
1. Clone the github project: https://github.tools.sap/S4-FIORI-CORE-4/i2d.pp.kab.manageproductionsupplyareass1
2. Run the app with mock server in debugging mode: npm run start-mock
3. Set break point in ProductionSupplyArea.js in the function executeAction
4. In the app (UI) press "Go" button in List Report and press any item in the table to navigate to Object Page
5. Press "Edit" button to switch on edit mode
6. Press "Create Address" or "Delete Address" button to trigger the action.
7. Then you can see the value of parameter keys

### Expected results
keys = {IsActiveEntity: false, Plant: 'Pla1', ProductionSupplyArea: 'Productio1'}

### Actual results
keys = {IsActiveEntity: 'false', Plant: ''Pla1'', ProductionSupplyArea: ''Productio1''}

### Screenshots
![image](https://user-images.githubusercontent.com/55737520/232795977-578ba369-74f3-4374-b138-99ef9f6bfedf.png)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [X] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by drktfl** [comment]
The additional apostrophes are now removed (starting from version 2.1.99). Please note:

> keys = {IsActiveEntity: false, Plant: 'Pla1', ProductionSupplyArea: 'Productio1'}

`IsActiveEntity` will not be passed as a boolean `false`, but still arrive as a string `"false"`

**Comment by drktfl** [comment]
Key values are now parsed to numbers, booleans or strings. Please use version 2.1.101 to see an effect.
