### ISSUE TITLE
Wrong __metadata id/uri when using a combined key with string and int32

### ISSUE THREAD

**Issue by sb-aigh** [SAP/open-ux-odata#641]
### Description
Assuming one has defined a V2 entity with a combined key containing string and int32, like....
```
	<EntityType Name="MyEntity">
		<Key>
			<PropertyRef Name="ObjectId"/>
			<PropertyRef Name="Id"/>
			<PropertyRef Name="Version"/>
		</Key>
		<Property Name="ObjectId" Type="Edm.String" Nullable="false" MaxLength="255"/>
		<Property Name="Id" Type="Edm.Int32" Nullable="false"/>
		<Property Name="Version" Type="Edm.String" Nullable="false" MaxLength="18"/>
		<Property Name="Type" Type="Edm.String" Nullable="false" MaxLength="40"/>
		<Property Name="Sequence" Type="Edm.Int32" Nullable="true"/>
		<NavigationProperty Name="MySubEntity" Relationship="MyEntityToMySubEntity" FromRole="FromRole_MyEntityToMySubEntity" ToRole="ToRole_MyEntityToMySubEntity"/>
	</EntityType>
```
As far as I could see, the function `addV2Metadata` in [dataAccess.ts](https://github.com/SAP/open-ux-odata/blob/490c2a7fe6eab219a4e2b9c85477c2a25d5f2f46/packages/fe-mockserver-core/src/data/dataAccess.ts#L961) converts all keys to strings with single quotes.
In the app, when accessing the UI context with path `/MyEntities(ObjectId='3cd0813b921744539da05c34d72ec7fa',Id=4,Version='000002')`, no data is returned as the mockserver created  the mockdata with key `/MyEntities(ObjectId='3cd0813b921744539da05c34d72ec7fa',Id='4',Version='000002')` (**Id=4** versus **Id='4'**).

### Expected results
The __metadata id/uri should have the correct path with `Id` having an integer value. Maybe there is a hook to influence the mockdata creation and/or to adjust the __metadata values?

**Comment by nlunets** [comment]
Fixed with [@sap-ux/ui5-middleware-fe-mockserver@2.1.109](https://github.com/SAP/open-ux-odata/releases/tag/%40sap-ux%2Fui5-middleware-fe-mockserver%402.1.109)
