### ISSUE TITLE
BUG - edmx parser: duplicate alias leads to exception

### ISSUE THREAD

**Issue by schreckstefan** [SAP/open-ux-odata#653]
### Related issues
https://itsm.services.sap/now/workspace/agent/record/sn_customerservice_case/1b8fff65972321109da3f9300153afb0
https://github.wdf.sap.corp/ux-engineering/tools-suite/issues/25299

### Description
Under certain circumstances the SAP Gateway seems to return metadata documents with duplicate edmx references.
This root cause must be solved of course, I thus forwarded the original customer ticket to the Gateway component.
Indeed, there is an agreement at our Fiori Tools group that such a duplication shall not lead to any exception at our tools.
We should be fault-tolerant here.

I now debugged the situation at our PageMap and could find out that an exception gets triggered at the edmx parser (to be exact:  DataStore.js > addFileReference). This exception is not caught smoothly but leads to an incomplete metadata document getting returned, subsequently causing some trouble at various  tools.
On the other side, the Fiori Elments run-time has no problem with the situation, the app  is rendered correctly.

Thus, the edmx-parser should also be adapted to be fault-tolerant in this case.

### Steps to Reproduce
Refer to https://github.wdf.sap.corp/ux-engineering/tools-suite/issues/25299

### Expected results
The duplicate alias is ignored, and the full metadata document is returned.

### Actual results
Exception

### Screenshots
![image](https://github.com/SAP/open-ux-odata/assets/126068396/5ce592cc-0632-42b0-b110-d43b0691f67d)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [X] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by schreckstefan** [comment]
@nlunets

**Comment by nlunets** [comment]
@drktfl as i recall you added this one right ? I think i'm ok with it being removed but maybe there are some problems behind.
