### ISSUE TITLE
ui5-middleware-fe-mockserver - Missing documentation for unbound actions/function imports

### ISSUE THREAD

**Issue by jonaszuberbuehler** [SAP/open-ux-odata#662]
### **Issue Description**
From the examples on function imports it's unclear how to mock unbound actions. After debugging the mock server I've found out about the `EntityContainer.js` file (`DataAccess#performAction`). Some official documentation and/or examples about it would be helpful.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [X] Documentation is missing
- [ ] Other

**Comment by helencorrigan** [comment]
FYI @nlunets

**Comment by nlunets** [comment]
https://github.com/SAP/open-ux-odata/blob/main/docs/EntityContainerAPI.md

Referred to from

https://github.com/SAP/open-ux-odata/tree/main/packages/ui5-middleware-fe-mockserver
![image](https://github.com/SAP/open-ux-odata/assets/13470207/5e9c3939-a530-4ba8-a8cf-fd499898f90c)

-> https://github.com/SAP/open-ux-odata/blob/main/docs/DefiningMockdata.md

![image](https://github.com/SAP/open-ux-odata/assets/13470207/59be864a-2305-40d2-ac4e-3864b68fc253)

**Comment by nlunets** [comment]
@jonaszuberbuehler the documentation exists already, and can be accessed rather easily from the readme of the mockserver middleware, so i'm not sure what else we can do here.

**Comment by jonaszuberbuehler** [comment]
@nlunets Thanks, must have missed that somehow.
