### ISSUE TITLE
BUG - Wrong __metadata id/uri when using a single key with Edm.Guid

### ISSUE THREAD

**Issue by sb-aigh** [SAP/open-ux-odata#666]
### Description
Assuming one has defined a V2 entity with a single key of type Edm.Guid, like....
```
<EntityType Name="MyEntity">
	<Key>
		<PropertyRef Name="ID"/>
	</Key>
	<Property Name="ID" Type="Edm.Guid" Nullable="false"/>
	...
</EntityType>
```
The function `addV2Metadata` in [dataAccess.ts](https://github.com/SAP/open-ux-odata/blob/490c2a7fe6eab219a4e2b9c85477c2a25d5f2f46/packages/fe-mockserver-core/src/data/dataAccess.ts#L957) composes an uri like `/MyEntities(3cd0813b921744539da05c34d72ec7fa)` which is not correct. I think, the metadata uri should have the format `/MyEntities(guid'3cd0813b921744539da05c34d72ec7fa')` in that case.

### Expected results
The __metadata id/uri should have the correct path with `ID` having the right format like `/MyEntities(guid'3cd0813b921744539da05c34d72ec7fa')`.

**Comment by sb-aigh** [comment]
Unfortunately, the patch does not fix all scenarios. If the entity has just one key using Edm.Guid then still the returned metadata is wrong. You need to add the same logic [here](https://github.com/SAP/open-ux-odata/blob/f95a5b4ff87ef220d9207a9fc8e739a885e9dd05/packages/fe-mockserver-core/src/data/dataAccess.ts#L957) for branch `if (Object.keys(currentKeys).length === 1) {` probably?!

**Comment by jonaszuberbuehler** [comment]
This doesn't only apply to `Edm.Guid`, the single quotes are also missing for `Edm.String` as an example.

**Comment by nlunets** [comment]
Most likely fixed by [@sap-ux/ui5-middleware-fe-mockserver@2.1.115]
