### ISSUE TITLE
BUG - [Mockserver] empty key provided in executeAction

### ISSUE THREAD

**Issue by c-kobo** [SAP/open-ux-odata#669]
### Description
For a mocked action in an FPM Explorer sample, executeAction is being called with a key string that is incomplete (key empty, only value provided.
![image](https://github.com/SAP/open-ux-odata/assets/39270906/ba5205fe-e6e6-4ce9-8ada-c27249c6796f)

This leads to subsequent issues when trying the fetchEntries based on the provided key.

### Steps to Reproduce
1. Go to http://localhost:8080/test-resources/sap/fe/core/fpmExplorer/index.html#/advancedFeatures/guidance/guidanceSideEffects
2. Expand side effects sample 7 
3. Select a business partner in the drop down
4. Press 'Delete Business Partner'

An error is thrown. Handler is implemented in file fpmExplorer/topics/advancedFeatures/guidanceSideEffects/localService/RootEntity.ts

### Expected results

keys provided to executeAction shall not contain empty key string

### Screenshots
![image](https://github.com/SAP/open-ux-odata/assets/39270906/68bbd3ea-c51e-4e96-bbf1-84ebde53bb2c)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Can you try updating to the latest version ? 
We recently changed something there that should improve the quality of the keys in the action calls

**Comment by c-kobo** [comment]
@nlunets tested locally with "@sap-ux/ui5-middleware-fe-mockserver": "^2.1.113", error persists.

**Comment by c-kobo** [comment]
Will be fixed in the FPM Explorer sample with change 5933560
