### ISSUE TITLE
BUG -  fe-mockserver-core's DataAccess class delivers wrong v2 metadata

### ISSUE THREAD

**Issue by nhahn1312** [SAP/open-ux-odata#671]
### Description
The addV2Metadata method of the [DataAccess](https://github.com/SAP/open-ux-odata/blob/main/packages/fe-mockserver-core/src/data/dataAccess.ts) class returns a wrong metadata uri, if a boolean key is involved. The method should format the keys according to the [Abstract Type System Document (6. Primitive Data Types)](https://www.odata.org/documentation/odata-version-2-0/overview/#AbstractTypeSystem). Instead it formats a boolean value as 'true' or 'false'.

### Expected results

`"__metadata": {
	"id": "/myEntity(myID=guid'e7a5fb1d-9ba6-474d-a7ba-8953cd83f355',IsActiveEntity=true)",
	"uri": "/myEntity(myID=guid'e7a5fb1d-9ba6-474d-a7ba-8953cd83f355',IsActiveEntity=true)",
	"type": "myType",		
},`

### Actual results

`"__metadata": {
	"id": "/myEntity(myID=guid'e7a5fb1d-9ba6-474d-a7ba-8953cd83f355',IsActiveEntity='true')",
	"uri": "/myEntity(myID=guid'e7a5fb1d-9ba6-474d-a7ba-8953cd83f355',IsActiveEntity='true')",
	"type": "myType",		
},`

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
This is fixed in version @sap-ux/ui5-middleware-fe-mockserver@2.1.114
