### ISSUE TITLE
BUG - Influencing V2 entity set behavior throws error

### ISSUE THREAD

**Issue by sb-aigh** [SAP/open-ux-odata#673]
### Description
When using the feature to influence entity set behavior using <EntitySet>.js file implementing function executeAction(), the mockserver returns an error like `Cannot read properties of undefined (reading 'toString')` for unbound actions (V2).
The issue seems to be located in [dataAccess.ts](https://github.com/SAP/open-ux-odata/blob/f95a5b4ff87ef220d9207a9fc8e739a885e9dd05/packages/fe-mockserver-core/src/data/dataAccess.ts#L196). The resulting outdata is a not resolved here, hence causing the below coding to fail.

### Expected results
Mockserver returns the custom data returned in function executeAction().

### Actual results
Mockserver returns an error.

#### Version/Components/Environment	
2.1.114

**Comment by nlunets** [comment]
What does your executeAction looks like, it's a bit difficult to judge where the bug might be without this as we have tests validating the behavior of the executeAction in v2 on EntityContainer.

**Comment by sb-aigh** [comment]
The function simply looks like the following:
```
module.exports = {

    executeAction: function (actionDefinition, _actionData, _keys, _odataRequest) {
        if (actionDefinition.name === 'MyUnboundAction') {
            return {
                "ID": "00a4c48c-0dfc-4507-abc6-9b54a431b788",
                "property1": "LDH75DRPTNDHDCERTQWES7AFVY",
                "property2": "EUR"
            };
        }
    }
};
```

**Comment by nlunets** [comment]
Most likely fixed by [@sap-ux/ui5-middleware-fe-mockserver@2.1.115]
