### ISSUE TITLE
BUG - @sap-ux/ui5-middleware-fe-mockserver | groupby clause for fields containing the string 'desc' fails

### ISSUE THREAD

**Issue by mirko1989** [SAP/open-ux-odata#676]
### Related Feature
Feature request: -

### Description
When running the mock server @sap-ux/ui5-middleware-fe-mockserver for OData V4 services there is a parsing error when doing a `groupby` expression for a field which contains the string ‘*desc*’, e.g. **desc**ription.

### Steps to Reproduce
1. Create a service with an entity set that has a field named 'description'.
2. Start the mock server
3. Do a groupby url expression on the field 'description', e.g. http://localhost:8080/service/Test?$apply=groupby((description))
4. Check the running terminal for uncaught MismatchedTokenException.
5. Check browser for message 'Parsing errors detected'

### Expected results

Groupby is working on arbitrary named fields.

### Actual results

Mock server breaks for fields containing 'desc' in their name.

### Screenshots
![image](https://github.com/SAP/open-ux-odata/assets/40920863/dbe217af-6864-4df0-bc89-faedddfd43ea)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [x] Windows ( WSL2 running Ubuntu 22.04.3 LTS )
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Should be fixed with [@sap-ux/ui5-middleware-fe-mockserver@2.1.120]
