### ISSUE TITLE
BUG - Data generated by mock server is longer than the `MaxLength` specified in the metadata.

### ISSUE THREAD

**Issue by sz3lbi** [SAP/open-ux-odata#709]
### Related Feature
Feature request: N/A

### Description
I am using `sap-fe-mockserver` with the `generateMockData: true` option enabled for services used in the application.  
One of the services has a field in the metadata like this:
```xml
<Property Name="Arbpl" Type="Edm.String" Nullable="false" MaxLength="8" sap:display-format="UpperCase" sap:label="Arbeitsplatz"/>
```
You can see that the `MaxLength` property is set to `8`. However, the values generated by the middleware are longer, e.g. `"Arbpl": "Arbpl_130"` (9 characters).

### Steps to Reproduce
1. Specify a metadata with a field that has `MaxLength` set to some low number.
2. Set the `generateMockData` property to `true`.
3. Open the generated local OData and see that the generated data is longer than the `MaxLength` value.

### Expected results
Value that satisfies the constraints specified in the metadata.

### Actual results
Value that does not satisfy the constraints specified in the metadata.

### Screenshots
N/A

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [X] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by helencorrigan** [comment]
FYI @nlunets

**Comment by nlunets** [comment]
Fixed with @sap-ux/ui5-middleware-fe-mockserver": "^2.1.125
