### ISSUE TITLE
BUG - Not eq operator for id (UUID) field parsing error

### ISSUE THREAD

**Issue by swayongshen** [SAP/open-ux-odata#717]
### Description
Mockserver unable to parse this request, specifically at the `$filter=not%20(id%20eq%20631e9c9f-b3f7-47e2-aebb-ce76802f883a%20or%20id%20eq%206e67a558-5421-41da-8314-3636bfe9124b)` section.

`InspectionResults?$orderby=id&$select=executedOn,id,imageUrl,status&$expand=inspectionView($select=id,name),prediction($select=id,rating,result),sfc($select=id,name)&$filter=not%20(id%20eq%20631e9c9f-b3f7-47e2-aebb-ce76802f883a%20or%20id%20eq%206e67a558-5421-41da-8314-3636bfe9124b)&$skip=18&$top=2`

However, a CAP CDS server with the exact same metadata is able to parse this request that is automatically generated by SAP UI5 after deleting an ODataContext.

### Steps to Reproduce
1. Call the API endpoint of the mockserver using the request URL

### Expected results
Able to receive the GET response.

### Actual results
Parsing error

### Screenshots
If applicable, add screenshots to help explain the problem.
<img width="798" alt="image" src="https://github.com/SAP/open-ux-odata/assets/52824657/c6215851-41b5-4753-823b-581100d16fce">

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [X] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Fixed with @sap-ux/ui5-middleware-fe-mockserver": "^2.1.125
