### ISSUE TITLE
BUG - Mockserver for oData v2 does not encode "/" if multiple keys are used

### ISSUE THREAD

**Issue by DanielJakobs** [SAP/open-ux-odata#748]
### Description
If I have a data model
Products
ProductsVersions

and a navigationProperty from Products to ProductsVersions using Name and Version as key,

the mockser does not encode slashes in the Name string. If you just use a single key the encode function will be called.

### Steps to Reproduce
Just open
@sap-ux/fe-mockserver-core/dist/data/dataAccess.js
and examine function getV2KeyString. It does not encode URI if the else-condition will be invoked.

![image](https://github.com/SAP/open-ux-odata/assets/6417510/42f9e8f7-a028-4583-927e-f3cbb67853cb)

### Expected results
All keys in the URI will be encoded

### Actual results
due to the missing encoding the odata model fails to set up correct data.
![image](https://github.com/SAP/open-ux-odata/assets/6417510/4cd44850-874d-4bf3-b883-99afd11110ec)

#### Version/Components/Environment	
        "@sap-ux/ui5-middleware-fe-mockserver": "^2.1.122",

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by helencorrigan** [comment]
FYI @nlunets
