### ISSUE TITLE
FEATURE - 

### ISSUE THREAD

**Issue by junwei-tj** [SAP/open-ux-odata#750]
_As a developer,
I want to modify the mock server on the fly during my Opa5 tests,
so that I can perform actions such as reverting data or mock error responses_

### Description

_What is the high level purpose and value of the feature?  The description should ensure that anyone reading understands what it is doing (at a high level) and most importantly why._
I have a UI5 application (developed in TypeScript) that uses Opa5 for integration testing. As I wrote my tests, I realised that
1) the test order sometimes affects whether all the journeys can pass. For example, say I have a list report page and an object page. I can change the status of the entities (e.g. from NEW -> APPROVED) in both the list page and object page. 
    - In the list page, I have a test to make sure filtering by NEW works by checking the correct number of results. 
    - If the detail page journey, which includes testing if the entity can be APPROVED, runs first, then the list page journey fails as the expected number of entities with the NEW status is now wrong.
2) I have tests to check if error handling is implemented correctly, that is if an error occurred, it should display a MessageBox. I am able to mock an error response using the mock server API for PATCH requests, but not for DELETE requests.

### Technical Design
_What modules need to be created or enhanced?_ 
_How would the functionality be exposed and how can it be consumed?_

### Acceptance Criteria
GivenWhenThen format (https://martinfowler.com/bliki/GivenWhenThen.html)

**Given** I have 2 Opa5 tests whose successful execution depends on which is ran first
**when** I execute a function that lets me change the mock data inside the tests
**then** my tests will pass regardless of the order it is ran first.

**Given** I have an Opa5 test that needs to mock an error response from the server
**when** I execute a function that lets me mock an error response
**then** my tests will run with the error response and check that it is handled properly.

### Tasks
- [ ] 
- [ ] Unit Tests added
- [ ] Test Cases defined

**Comment by nlunets** [comment]
Modifying mockserver on the fly to accomodate for test is not the recommended way to achieve what you want.
Intead we recommend that you define different set of mockdata using the `contextBasedIsolation` option.
Once this is enabled by passing the `sap-client=xxx` parameter, all request going into the mockserver will have this tenantId parameter available and each tenant will have it's own independent set of data (can be either the same or different)

You can see how this is used in practice here https://github.com/SAP/open-ux-odata/blob/15a26c5e3869067c90c5bc99afe4069223f74c6c/packages/fe-mockserver-core/test/unit/data/mockdata/MyRootEntity.js#L4

Regards
Nicolas

**Comment by junwei-tj** [comment]
Hi Nicolas, thanks for pointing out the use of `contextBasedIsolation`. It does seem useful for separating mock data for different test scenarios.

Currently, I am also facing another issue where I have to restart the mock server every time I re-run the integration tests, which I don't think `contextBasedIsolation` helps in this case. For example, I am testing if I can approve an entity, but I realised in my test I have written the assertion wrongly causing the test to fail (however the approve action works). Now, my entity has the status APPROVED, and to re-test this test case I have to restart the mock server again to change the status of my entity back to NEW. May I ask if you know of a way to work around this? Thank you!

**Comment by nlunets** [comment]
If you POST to $metadata/reload the mockdata will be reloaded, it is what is usually done in FioriElements based OPA test.
It's also part of the `BaseArrangements` class from sap.fe.test

**Comment by junwei-tj** [comment]
Thank you so much! I managed to get the reloading to work :)

Will be closing this issue now since the feature requests were solved with existing features
