### ISSUE TITLE
BUG - Default Values on Draft Creation

### ISSUE THREAD

**Issue by Tim-Riffelmacher-SAP** [SAP/open-ux-odata#785]
### Related Feature
n/a

### Description
When creating an empty draft the returned entity contains prefilled property values. The prefilled property values depend on the property type. For example: Given the property `description` of type `Edm.String` then the default value `""` is set in the draft entity. When we compare this to the behaviour of a 'real' CAP-backend-server (whether Node.js or Java), the property values are always set to `null` independent of their type. Only exception is when default values are specified in the given metadata files (e.g. `IsActiveEntity=true`).

This can result in an error when executing OPA-tests. For example: Given the property `ref_ID` of type `Edm.Guid`, that references another entity, is set to `""` on draft creation. In the browser (given a Fiori Elements application) this `ref_ID` is trying to be resolved (due to a value help field), which leads to an OData request containing `...&$filter=ID%20eq%20&$...`. This produces an error on server-side because the `eq` operator is followed by an empty string `""`. If `ref_ID` would have been `null` there would have been no try in resolving it, thus no error.

### Steps to Reproduce
Steps to reproduce the behaviour:
1. Create an empty draft via `POST <service-URL>/<entity-name>` using the mocked backend.
2. Create an empty draft via `POST <service-URL>/<entity-name>` using the 'real' backend.
3. Compare both drafts.

### Expected results
The property values of the returned draft entity should always be `null`, if no default value is provided by the given metadata.

### Actual results
The property values of the returned draft entity depend on their type, if no default value is provided by the given metadata.

### Screenshots
n/a

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Hello @Tim-Riffelmacher-SAP you are correct the nullable values could be null.

Changing this for everyone might be a breaking change though so i won't do it for everyone but instead provide you with an option, would that be ok for you ?

**Comment by nlunets** [comment]
Option `forceNullableValuesToNull` introduced with @sap-ux/ui5-middleware-fe-mockserver@2.2.29

**Comment by Tim-Riffelmacher-SAP** [comment]
Thanks a lot for providing this option!
