### ISSUE TITLE
BUG - $count queries are returned including CR + LF

### ISSUE THREAD

**Issue by heimwege** [SAP/open-ux-odata#811]
hey hey 👋🏻 

A `$count` query (at least for an odata v2 request) does not only return the actual count but also '\r\n'.

Sample:

request: `MyEntity/$count?$filter=name%20eq%20%27Foo%27%20and%20id%20ne%20guid%27b31b9366-7843-4515-a46d-ac197a6c49b0%27`

response: `'0\r\n'`

Currently we overcome this by ignoring it on the application side (`sCount.replace(/\r?\n|\r/,'') === '0'`), but as this is not required when working with the real CAP backend we would of course prefer if the mockserver would not add the CR + LF so that the mockserver specific code is not needed in the application.

### Expected results

response: `'0'`

### Actual results

response: `'0\r\n'`

### Screenshots

<img width="153" alt="image" src="https://github.com/SAP/open-ux-odata/assets/73878785/c043b88b-0e74-41f1-952a-958658714bd9">

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [X] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Can't reproduce this when checking on my machine with v2 or v4 samples.
Could you share a sample project where this happens ?

**Comment by heimwege** [comment]
Can confirm the fix works 👍🏻
