### ISSUE TITLE
Not possible to throw error while fetching entries

### ISSUE THREAD

**Issue by AdrianDengusiak** [SAP/open-ux-odata#814]
### **Not possible to throw error in getInitialDataSet**
I'd like to throw an error when get entity set is called by application. My goal is to simulate error for different scenarios. 

Documentation says:
_The entity interface allow you then to access the standard function (addEntry, fetchEntries, ...) to manipulate the mockdata of the application._

But **fetchEntries** is not mentioned in any of the API documenatations.

I also can't throw an error in **getInitialDataSet**.

How can I achievie this for get entity set / get entity? Is there any hook or workaround?

### **Issue Type**

- [X] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [X] Other

**Comment by nlunets** [comment]
fetchEntries exist and is not recommended to be overriden for 99% of the scenarios :)
But in your case that would be the correct one to throw an error in.

GetInitialDataSet is used to prefill the overall data, so if you break in this one that's just the entire service breaking,  which is usually not wanted.

Can you check with an override to fetchEntries and if that's the case i'll adjust the documentation

**Comment by nlunets** [comment]
@AdrianDengusiak did you check this meanwhile ?

**Comment by nlunets** [comment]
Recently we also introduced `onAfterRead` which can also be used to do things, including throwing errors :)

 async onAfterRead(data: object, _odataRequest: ODataRequest): Promise<object> {
        return data;
    }
