### ISSUE TITLE
BUG - @sap-ux/fe-mockserver-plugin-cds i18n handling

### ISSUE THREAD

**Issue by heimwege** [SAP/open-ux-odata#834]
### Description

i18n annotations in the data model, e.g.

`/srv/i18n/i18n.properties`
```
name=Name
```

`/db/data-model.cds`
```
entity Samples : cuid, managed {
    name     : String(50) @title : '{i18n>name}'; // <-- this one here
    comments : composition of many Comments on comments.sample = $self;
}
```

are not being resolved in the metadata

```
<Annotations Target="CapFeTsSampleService.Samples/name">
        <Annotation Term="Common.Label" String="{i18n>name}"/>
</Annotations>
```

whereas the `cds build` resolves it to

```
<Annotations Target="CapFeTsSampleService.Samples/name">
        <Annotation Term="Common.Label" String="Name"/>
</Annotations>
```

The i18n used in the UI annotations (referring to `./webapp/i18n/i18n.properties`) work fine

### Expected results

UI displaying `Name` as table column header (e.g. when property is used as LineItem)

### Actual results

UI displays `{i18n>name}` as table column header (e.g. when property is used as LineItem)

### Screenshots
![image](https://github.com/user-attachments/assets/a06f70d1-4ac6-4520-be45-ba04ff858e6a)

![image](https://github.com/user-attachments/assets/9a60213f-fd04-4538-8eac-a16a8a482d0c)

table title i18n coming from  `./webapp/i18n/i18n.properties` 👍🏻 
table column headers coming from `/srv/i18n/i18n.properties` or even directly from CAP (using `@sap/cds/common`) like `ChangedBy` 👎🏻 

Not sure where the path `../i18n/i18n.properties` is coming from 🤷🏻 

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [X] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
That would be nice, but the cds-compiler API doesn't seem to support the i18n, even if we pass them directly...
We could replace and parse in the target EDMX but that becomes a bigger work :/

**Comment by heimwege** [comment]
Oh no. This might be a real blocker for using the plugin because e.g. OPA5 tests might fail if the text is not as expected. I'll open a CAP issue and ask the guys? They must do it somewhere along the `cds build` as well 🤷🏻

**Comment by nlunets** [comment]
Let me check for a dirty solution :)

**Comment by heimwege** [comment]
Ok, then I'll wait for your feedback 🐱

**Comment by heimwege** [comment]
`1.2.1` looks much better 🥳 i18n is shown but there are some superfluous `,` (just for some not all 🤷🏻)

![image](https://github.com/user-attachments/assets/4975822a-100f-4b05-b82b-484f4adfc556)

**Comment by nlunets** [comment]
That might be due to what i copied ;o

**Comment by heimwege** [comment]
The `,` is gone in `1.2.2`. And I adjusted the i18n keys to ese the identification (`samples` and `Samples` looks quite the same 🙈). So now we're at
![image](https://github.com/user-attachments/assets/ede2b1f0-3c3c-4876-8736-d4c318edbeb9)

The cds common stuff works 👍🏻 but the annotations from `db/data-model.cds` (`{i18n>nameI18n}`) and `app/samples/ui-annotations.cds` (`{i18n>samplesI18n}`) are using the i18n key instead of the value as fallback because loadI18nMap [is being called](https://github.com/SAP/open-ux-odata/blob/9374723e84e9cd8903e59d0a9860075b609fc8d8/packages/fe-mockserver-plugin-cds/src/index.ts#L85) with `dirName` pointing to the app folder `<someLocalPath>\cap-fe-ts-sample\app\samples`. Hence all the i18n paths from [loadI18nMap](https://github.com/SAP/open-ux-odata/blob/main/packages/fe-mockserver-plugin-cds/src/index.ts#L40) do not point to a file 😢 

Maybe [project-access](https://github.com/SAP/open-ux-tools/tree/main/packages/project-access) or [i18n](https://github.com/SAP/open-ux-tools/tree/main/packages/i18n) could help to find the i18n file(s)?

Or the `location` from the [csn](https://github.com/SAP/open-ux-odata/blob/main/packages/fe-mockserver-plugin-cds/src/index.ts#L84) could be used as starting point 
![image](https://github.com/user-attachments/assets/a229060e-e6e8-4dc2-ba99-190c0e35d3e3)

Or add hard coded `/webapp/i18n` and `/../../srv/i18n`. That worked for me as well 🐱

**Comment by nlunets** [comment]
Dependencies are not really possible or wanted as they tend to create dedicated `fs` requirement :)
Looking at the cds documentation /webapp/i18n would not be considered, maybe /../../srv/i18n because this file is being loaded ....
Do you have a sample repo that i can check directly ? would avoid more back and forth :)

**Comment by heimwege** [comment]
Here's the respective branch: https://github.com/heimwege/cap-node-fe-ts-sample/tree/Fe-mockserver-plugin-cds
just `npm run install:all` and `npm run ui:mockserver` then you see

<img width="1067" alt="image" src="https://github.com/user-attachments/assets/24f7a520-64cf-4fca-a691-1824dae937cd">

The green marked texts are wrong (from `srv/i18n/i18n.properties`):
`samples` should be `Samples_i18n`
`name` should be `Name_i18n`

**Comment by nlunets** [comment]
@heimwege i feel like i forgot something here, did you still expect something here ?

**Comment by heimwege** [comment]
> @heimwege i feel like i forgot something here, did you still expect something here ?

The i18n issue described in the very last comment still persists. I think your idea was to pass the i18n path as an optional parameter in the yaml config or something like that. Currently the srv/i18n seems not to be taken into account in the linked sample repo

**Comment by nlunets** [comment]
I prepared now https://github.com/SAP/open-ux-odata/pull/885 can you check if it helps ? :)

**Comment by nlunets** [comment]
All done starting version [@sap-ux/ui5-middleware-fe-mockserver@2.2.79]
