### ISSUE TITLE
BUG - Incorrect response coming when using mock server response

### ISSUE THREAD

**Issue by abinashstack** [SAP/open-ux-odata#836]
### Related Feature
Feature request: 13

### Screenshots
![image](https://github.com/user-attachments/assets/9cc4589a-9de1-434f-a7ae-dbd329addd43)
![image](https://github.com/user-attachments/assets/fab82842-06f9-487c-8e89-29c35ca48e98)

### Description

In the getUnifiedResponse() method, the error batch412Response has been hardcoded, so the error message comes along with the success message like mentioned below:

`JSON file: 
{"d":{"ExtendFlxCnsGroupValidity_ac":false,"SetFlxCnsToInactive_ac":false,"Update_mc":false,"to_Constraints_oc":false,"AdvncdPlngFlxCnsUUID":"60ad270d-9ef8-4070-9a67-761b1b2e2ec6","AdvncdPlngFlxCnsKey":"LOCPRD","PlanningVersionExternal":"NwDGGYKiyy","AdvncdPlngSimulationVersion":"cNEuTCdXLWhwkNJqBzGLXzMTVMIWmGCo1","AdvncdPlngFlxCnsGrpId":"$000000001","AdvncdPlngFlxCnsGrpIdReference":"","AdvncdPlngFlxCnsKeyDesc":"","AdvancedPlanningProductName":"AdvancedPlanningProductCOPY1","AdvancedPlanningFilterLocation":"AdvancedPlanningFil1","AdvncdPlngSupNameSrce":"","AdvncdPlngSOSDesc":"","AdvncdPlngFlxCnsIdStrtDteTme":"/Date(2062578527000)/","AdvncdPlngFlxCnsIdEndDteTme":"/Date(2272374481000)/","AdvncdPlngFlxCnsRcrrc":"Q","AdvncdPlngFlxCnsRcrrcDesc":"","AdvncdPlngLstChgDteTme":"/Date(1721234243310+0000)/","AdvncdPlngLstChgPersn":"","AdvncdPlngFlxCnsIdDesc":"AdvncdPlngFlxCnsRcrrcDesc1","to_Constraints":[{"PlanningVersionExternal":"NwDGGYKiyy","AdvncdPlngSimulationVersion":"cNEuTCdXLWhwkNJqBzGLXzMTVMIWmGCo1","AdvncdPlngFlxCnsKey":"LOCPRD","AdvncdPlngFlxCnsGrpId":"$000000001","AdvncdPlngFlxCnsRcrrc":"Q","AdvncdPlngStrtDteTme":"/Date(2062578527000)/","AdvncdPlngEndDteTme":"/Date(2272374481000)/","AdvncdPlngFlxCnsMinQty":200,"AdvncdPlngFlxCnsMinUnit":"EA","AdvncdPlngFlxCnsMaxQty":500,"AdvncdPlngFlxCnsMaxUnit":"EA","AdvncdPlngFlxCnsTgtQty":300,"AdvncdPlngFlxCnsTgtUnit":"EA","AdvncdPlngFlxCnsFrequency":"1"}],"__metadata":{"id":"/sap/opu/odata/sap/UI_SCM_FLEX_CONSTR_V2//Main(AdvncdPlngFlxCnsKey='LOCPRD',PlanningVersionExternal='NwDGGYKiyy',AdvncdPlngSimulationVersion='cNEuTCdXLWhwkNJqBzGLXzMTVMIWmGCo1',AdvncdPlngFlxCnsGrpId='%24000000001',AdvncdPlngFlxCnsUUID=guid'60ad270d-9ef8-4070-9a67-761b1b2e2ec6')","uri":"/sap/opu/odata/sap/UI_SCM_FLEX_CONSTR_V2//Main(AdvncdPlngFlxCnsKey='LOCPRD',PlanningVersionExternal='NwDGGYKiyy',AdvncdPlngSimulationVersion='cNEuTCdXLWhwkNJqBzGLXzMTVMIWmGCo1',AdvncdPlngFlxCnsGrpId='%24000000001',AdvncdPlngFlxCnsUUID=guid'60ad270d-9ef8-4070-9a67-761b1b2e2ec6')","type":"cds_ui_scm_flex_constr.MainType"}}}
 
{"error":{"code":"","message":"","severity":"","details":[]}}`

So, it is going and throwing JSON parse error, saying "Unexpected non-whitespace character after JSON at position xxxx".

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [X] Mac OS   - ^2.2.52
- [X] Windows - ^2.2.52
- [ ] Other

`"@sap-ux/ui5-middleware-fe-mockserver": "^2.2.43"`

**Comment by otsquest101** [comment]
Hi @abinashstack I have raised a pull request already which will fix this issue : https://github.com/SAP/open-ux-odata/pull/835

**Comment by abinashstack** [comment]
Thanks @otsquest101

**Comment by abinashstack** [comment]
Closing this bug as the issue has been fixed in the latest publish. Thanks
