### ISSUE TITLE
[Mockserver] BUG - Filter by gt not working for double value

### ISSUE THREAD

**Issue by swayongshen** [SAP/open-ux-odata#840]
### Related Feature
Mockserver

### Description
A clear description of what the bug is.

`http://.../X(86c532c1-5baf-4c39-8349-c5b428c4ae41)/ncResults?$expand=groundTruthBoundingBox,predictedBoundingBox&$orderby=operatorResult_code,className&$select=ID,className,hit,ncName,operatorResult_code,prediction,threshold&$filter=prediction%20gt%20100&$skip=0&$top=100`

For the above request, we expect to fetch the `ncResults` for an `X` where `ncResult[0].prediction` will be greater than 100, but we are still receiving ncResults with `ncResult[0].prediction` less than or equal to 100. The metadata type of `prediction` is `Edm.Double`.

### Expected results
Filtering with gt/lt/eq on a double typed field should work.

### Actual results
Does not work as intended

### Screenshots
If applicable, add screenshots to help explain the problem.

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [ ] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
I've added a log as part of [@sap-ux/ui5-middleware-fe-mockserver@2.2.75]
