### ISSUE TITLE
BUG - annotation-converter exception when resolving references

### ISSUE THREAD

**Issue by schreckstefan** [SAP/open-ux-odata#847]
### Related Feature
Support of freestyle apps by Fiori Tools

### Description
While testing, I generated a test app with the app generator.
I used the basic template, but an ALP mock service for it.
When trying to open the Page Map for it, it fails with an exception.

![image](https://github.com/user-attachments/assets/3be8efca-0157-44d5-8b00-dc6d526498fc)

Reason is an exception at sap-ux/annotation-converter:

<img width="1406" alt="Screenshot 2024-08-23 at 10 52 12" src="https://github.com/user-attachments/assets/4d32f2a0-8dbb-482b-b9aa-e255b5ce58c6">

As a result, the schemas and configs cannot be generated by sap/ux-specification:
<img width="911" alt="image" src="https://github.com/user-attachments/assets/6063c3f3-e0d7-4087-88d1-2a3f3ea18b93">

### Steps to Reproduce
0. Open VSCode and install the SAP Fiori Tools - Extension Pack
1. Open the test app
[basicwithservice2208-2024-08-230855.zip](https://github.com/user-attachments/files/16726232/basicwithservice2208-2024-08-230855.zip)
2. Use command "Fiori: Show Page Map"
3. See error

### Expected results
The given alis definitions look OK and should get resolved

### Actual results
Exception

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [X] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Hi @schreckstefan i just checked the part which are specific to the annotation converter and loading and processing this file works well on the latest version.

My assumption is that you are not calling this properly.
Looking at the failing code and the error message i can only imagine that the `references` from your input type is a readonly variable, when we're expecting it not to be.

Parsing with edmx-parser (which is the standard implementation) and converting works fine.
Please have a look on your side and close this issue when that's done :)

**Comment by schreckstefan** [comment]
Hi @nlunets ,
The coding did not change on our side since a while:
` converterOutput = convert(mergeParser(...parseResult));`
Even if I change this to   
```
let mergedParserResult = mergeParser(...parseResult);
converterOutput = convert(mergedParserResult);
```
I run into the same error.

**Comment by nlunets** [comment]
@schreckstefan the problem on your side occurs because there is no references in this file, while i assume all the other you tested had some.

**Comment by schreckstefan** [comment]
@nlunets  Yes, you are right. The app was corrupted somehow. Does not appear with newly generated app.
Let me close the issue - if I can reproduce in future, I will clarif ywith the app gen colleagues.

**Comment by schreckstefan** [comment]
Sorry Nicolas, 
But a [new issue ](https://github.wdf.sap.corp/ux-engineering/tools-suite/issues/31007) appeared which describes the same problem, so we have to find a solution for it.
Could you please test the conversion of [project2-2024-08-221334.zip](https://github.wdf.sap.corp/ux-engineering/tools-suite/files/66047/project2-2024-08-221334.zip)?
Question is why you need to manipulate the original file at all, by adding references, which is the Northwind model that looks consistent.

And finally the question is why my workaound, as describe in https://github.com/SAP/open-ux-odata/issues/847#issuecomment-2310075875, did not have any effect.

Additional note:
https://github.wdf.sap.corp/ux-engineering/specification is still using annotation-converter 0.8.15 and edmx-parser 0.7.1, as the upgrade to the latest versions also leads to issues. 
Reference: https://github.wdf.sap.corp/ux-engineering/specification/pull/2765
Many of our test-projects fail with the new versions, I am still analyzing what happens.

**Comment by nlunets** [comment]
The inputs are modified because if we need to writeback, we need the references we introduced.
I can only reproduce the error if I deliberately `freeze` the input.
I can try to make it so that even this case works ... let me see

**Comment by schreckstefan** [comment]
You just updated dependencies? Ok, let me check. As mentioned, there had been some issues when I tried to apply 0.9.1 before. Will keep you informed.

**Comment by nlunets** [comment]
no i patched the code :)

**Comment by schreckstefan** [comment]
Looks much better with 0.9.2, only one unit test failing ... let me check that one

**Comment by schreckstefan** [comment]
@nlunets 
Confirmation: the new version works well, it solves the problem, and I can ship the consumption of the latest versions
