### ISSUE TITLE
Link to SAP Fiori Tools Community returns query error

### ISSUE THREAD

**Issue by tobiashofmann** [SAP/open-ux-odata#874]
### **Issue Description**

Clicking on the link to the SAP Fiori Tools Community in the readme redirects to SCN, but the page shown is empty.

Readme: https://github.com/SAP/open-ux-odata/tree/main/packages/ui5-middleware-fe-mockserver

Link goes to: https://community.sap.com/search/?by=updated&ct=blog&mt=73555000100800002345

Message shown by SCN: **Empty search query. Please enter one or more keywords and try again.**

![image](https://github.com/user-attachments/assets/51ae5aed-5c2e-4b2f-8609-8e9d14dc9d2f)

I'd expect that some search result is shown.

### **Issue Type**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [X] Other

**Comment by helencorrigan** [comment]
FYI @nlunets

**Comment by nlunets** [comment]
@tobiasqueck you were the one adding this, do you have an updated link ?

**Comment by nlunets** [comment]
It's fixed now :)
Thanks @tobiashofmann
