### ISSUE TITLE
BUG - Not possible to have Criticality property value that is not a dynamic expression

### ISSUE THREAD

**Issue by voicis** [SAP/open-ux-odata#881]
### Description
Using latest `@sap-ux/vocabularies-types` package it is not possible to set Criticality value that is not a dynamic expression anymore.

### Steps to Reproduce
1. Use the following snippet
```typescript
import type { DataPoint } from '@sap-ux/vocabularies-types/vocabularies/UI';
import type { AnnotationTerm } from '@sap-ux/vocabularies-types';

const dataPoint: AnnotationTerm<DataPoint> = {
    Criticality: 'UI.CriticalityType/Neutral'
};

```

### Expected results
It is possible to use constant values for Criticality.

### Actual results
There are Typescript compiler errors and it is not possible to set a value that is not a dynamic expression.

### Screenshots
![image](https://github.com/user-attachments/assets/bc6aa0a6-de91-4bbe-b7c0-d91162d2199f)

#### Version/Components/Environment	
Add any other context about the problem here
OS:                      
- [x] Mac OS
- [ ] Windows
- [ ] Other

### Problem
{describe the problem} 

### Fix
{describe the fix} 

### Why was it missed
{Some explanation why this issue might have been missed during normal development/testing cycle}  

### How can we avoid this
{if we don’t want to see this type of issues anymore what we should do to prevent}

**Comment by nlunets** [comment]
Hello @voicis , we had that discussion last year and i prepared https://github.com/SAP/open-ux-odata/pull/747 but you ended up not needing it :)
Do you need it now ?

**Comment by voicis** [comment]
Yes, that workaround seems to be no longer working and this proposed change would fix the issue.

**Comment by nlunets** [comment]
@voicis [@sap-ux/vocabularies-types@0.11.7](https://github.com/SAP/open-ux-odata/releases/tag/%40sap-ux%2Fvocabularies-types%400.11.7) should contain this :)
